# Generated by Django 6.1.1 on 2026-09-19 11:20

import django.core.validators
import django.db.models.deletion
import id_cards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, help_text="Auto-generated from the name (e.g. 'Science' → SCI). Leave blank to auto-generate.", max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level_type', models.CharField(choices=[('JSS', 'Junior Secondary School'), ('SSS', 'Senior Secondary School'), ('PRIMARY', 'Primary'), ('OTHER', 'Other')], default='JSS', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order — lower numbers appear first.')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Excel Junior Secondary School', max_length=200)),
                ('short_name', models.CharField(default='EJSS', help_text='Used as the ID prefix, e.g. EJSS-2026-001', max_length=50)),
                ('tagline', models.CharField(blank=True, default='Be strong and courageous, your works shall be rewarded', max_length=200)),
                ('scripture_ref', models.CharField(blank=True, default='2 Chronicles 15:7', max_length=100)),
                ('address', models.CharField(blank=True, default='', help_text='School address, shown on the back of the card.', max_length=200)),
                ('established', models.PositiveSmallIntegerField(blank=True, help_text='Year the school was established, e.g. 1995.', null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), id_cards.models.validate_image_size])),
                ('contact_phone_1', models.CharField(blank=True, help_text='Primary phone shown on the back of the card.', max_length=30)),
                ('contact_phone_2', models.CharField(blank=True, help_text='Secondary phone (optional).', max_length=30)),
                ('primary_color', models.CharField(default='#8B2020', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('secondary_color', models.CharField(default='#C87A2C', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('accent_color', models.CharField(default='#FBF6EC', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('text_color', models.CharField(default='#2A1810', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
            options={
                'verbose_name': 'School Branding',
                'verbose_name_plural': 'School Branding',
            },
        ),
        migrations.CreateModel(
            name='IDCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Faculty Card', max_length=100)),
                ('show_hologram', models.BooleanField(default=True)),
                ('show_gold_bar', models.BooleanField(default=True)),
                ('show_barcode', models.BooleanField(default=False)),
                ('show_terms', models.BooleanField(default=True, help_text='Show the terms of use section on the back of the card.')),
                ('show_issue_date', models.BooleanField(default=True, help_text='Show the issue date on the back of the card.')),
                ('show_expiry_date', models.BooleanField(default=True, help_text='Show the expiry date on the back of the card.')),
                ('show_authorized', models.BooleanField(default=True, help_text='Show the authorization statement on the back of the card.')),
                ('show_security', models.BooleanField(default=True, help_text='Show the security notice on the back of the card.')),
                ('default_terms', models.TextField(blank=True, default='This card is the property of the school and is not transferable. It must be carried at all times while on school premises and produced on demand by any authorized staff member.', help_text='Default terms of use text. Can be overridden per teacher.')),
                ('default_authorized_use', models.CharField(blank=True, default='Authorized for official school use only.', help_text='Default authorized-use statement.', max_length=200)),
                ('default_security', models.CharField(blank=True, default='If found, please return to the school office. Reward available.', help_text='Default security / lost-card notice.', max_length=200)),
                ('card_footer_text', models.CharField(default='STAFF IDENTIFICATION', max_length=100)),
                ('card_footer_subtext', models.CharField(default='(SEE REVERSE FOR DETAILS)', max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_template_name')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('designation', models.CharField(help_text='e.g. Senior Mathematics Teacher, Front Office Secretary', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg']), id_cards.models.validate_image_size])),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('SECRETARY', 'Secretary'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('COUNSELOR', 'Counselor'), ('LAB_TECH', 'Lab Technician'), ('ICT', 'ICT / Computer Staff'), ('SECURITY', 'Security'), ('CLEANER', 'Cleaning Staff'), ('DRIVER', 'Driver'), ('ADMIN', 'Administrator'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('BURSAR', 'Bursar'), ('OTHER', 'Other')], default='TEACHER', help_text='Staff role', max_length=30)),
                ('employee_id', models.CharField(blank=True, editable=False, help_text='Auto-generated from school short name and year', max_length=50, unique=True)),
                ('valid_thru', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number for emergency contact.', max_length=30)),
                ('issue_date', models.DateField(blank=True, help_text='Date the card was issued. Shown on the back.', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date the card expires. Shown on the back.', null=True)),
                ('id_card_terms', models.TextField(blank=True, help_text='Terms of use for this specific card. If left blank, the template default is used.')),
                ('authorized_use', models.CharField(blank=True, help_text='Authorization statement. If left blank, the template default is used.', max_length=200)),
                ('security', models.CharField(blank=True, help_text='Security / lost-card notice. If left blank, the template default is used.', max_length=200)),
                ('print_count', models.PositiveIntegerField(default=0, help_text='How many times this card has been printed.')),
                ('first_printed_at', models.DateTimeField(blank=True, help_text='When the card was first printed.', null=True)),
                ('last_printed_at', models.DateTimeField(blank=True, help_text='When the card was last printed.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='id_cards.department')),
                ('levels', models.ManyToManyField(blank=True, help_text='Levels this staff member handles (JSS1, SSS2, etc.)', related_name='teachers', to='id_cards.level')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='id_cards.idcardtemplate')),
            ],
            options={
                'verbose_name': 'Teacher / Staff',
                'verbose_name_plural': 'Teachers / Staff',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status'], name='id_cards_te_status_aa607a_idx'), models.Index(fields=['employee_id'], name='id_cards_te_employe_04335f_idx'), models.Index(fields=['-last_printed_at'], name='id_cards_te_last_pr_e23e7d_idx')],
            },
        ),
    ]
