# Generated by Django 6.1.1 on 2026-09-21 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_cards', '0002_teacher_default_authorized_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='default_authorized_use',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='default_security',
        ),
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='default_terms',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='authorized_use',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='default_authorized_use',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='default_security',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='default_terms',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id_card_terms',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='security',
        ),
        migrations.AddField(
            model_name='school',
            name='default_authorized_use',
            field=models.CharField(blank=True, default='Authorized for official school use only.', help_text='Shown on the back of every ID card.', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='default_security',
            field=models.CharField(blank=True, default='If found, please return to the school office. Reward available.', help_text='Optional security notice shown on the back of every card.', max_length=200),
        ),
        migrations.AddField(
            model_name='school',
            name='default_terms',
            field=models.TextField(blank=True, default='This card is the property of the school and is not transferable. It must be carried at all times while on school premises and produced on demand by any authorized staff member.', help_text='Shown on the back of every ID card.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='accent_color',
            field=models.CharField(default='#FDF6EC', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='#F58220', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='#6B3410', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='school',
            name='text_color',
            field=models.CharField(default='#3A1F0A', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #8B2020.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
