# Generated by Django 6.1.1 on 2026-09-19 11:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('id_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('admission_number', models.CharField(blank=True, editable=False, help_text='Auto-generated from school short name and year', max_length=50, unique=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=30)),
                ('valid_thru', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('blood_group', models.CharField(blank=True, choices=[('', '— Select Blood Group —'), ('O+', 'O+'), ('O-', 'O−'), ('A+', 'A+'), ('A-', 'A−'), ('B+', 'B+'), ('B-', 'B−'), ('AB+', 'AB+'), ('AB-', 'AB−')], default='', help_text='Shown on the back of the card.', max_length=3)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Phone number for emergency contact.', max_length=30)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('first_printed_at', models.DateTimeField(blank=True, null=True)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Optional: house, stream, or faculty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='id_cards.department')),
                ('level', models.ForeignKey(blank=True, help_text='Class/level the student is in (JSS1, SSS2, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='id_cards.level')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='id_cards.idcardtemplate')),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['status'], name='student_stu_status_b5bb73_idx'), models.Index(fields=['print_count'], name='student_stu_print_c_4ac0d2_idx'), models.Index(fields=['admission_number'], name='student_stu_admissi_609205_idx'), models.Index(fields=['level'], name='student_stu_level_i_d81912_idx')],
            },
        ),
    ]
